[package]
name = "rawscope-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
rawscope-core = { path = "../rawscope-core" }
rawscope-data = { path = "../rawscope-data" }
rawscope-gpu = { path = "../rawscope-gpu" }
wgpu = "29.0.3"

[dev-dependencies]
pollster = "0.4.0"
